/// Generated by spider on 2025-06-05 11:44:40.072439
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:comprobac/resources/resources.dart';

void main() {
  test('logo assets test', () {
    expect(File(Logo.logo).existsSync(), isTrue);
  });
}
