// Generated by spider on 2025-06-05 11:44:39.548588

part of 'resources.dart';

class Logo {
  Logo._();

  static const String logo = 'lib/assets/logo/logo.png';

  static const List<String> values = [logo];
}
